site_name: 0xbara
theme:
  logo: assets/images/logo.png
  name: material
  language: en
  favicon: assets/images/favicon.ico
  # Icons
  icon:
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
  # Features
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tabs.link
    - content.footnote.tooltips
    - content.tooltips
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.indexes
    - navigation.tabs.sticky
    - navigation.path
    - navigation.expand
    - navigation.tracking
    - navigation.top
    - navigation.footer
    - search
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide
  # Plugins
  plugins:
    - projects
    - optimize
    - tags
  # Colors
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: black
      accent: red
      toggle:
        icon: material/toggle-switch 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: red
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
# Markdown Extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
# Other
extra:
  social:
    - icon: simple/github
      link: https://github.com/0xbara
    - icon: simple/twitter
      link: https://x.com/0xbara
    - icon: simple/hackerone
      link: https://hackerone.com/0xbara
    - icon: simple/linkedin
      link: https://www.linkedin.com/in/agustinbaranowski/
